server {
    listen 443 ssl;
    listen [::]:443 ssl;

    http2 on;
    
    server_name blog.minjekim.dev;

    ssl_certificate     /etc/nginx/ssl/minjekim.dev.pem;
    ssl_certificate_key /etc/nginx/ssl/minjekim.dev.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://172.22.1.15:8080;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $realip_remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}